package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeNegativeBalanceFundingCost;
import com.google.backend.trading.dao.model.TradeNegativeBalanceFundingCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeNegativeBalanceFundingCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    long countByExample(TradeNegativeBalanceFundingCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int deleteByExample(TradeNegativeBalanceFundingCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int insert(TradeNegativeBalanceFundingCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int insertSelective(TradeNegativeBalanceFundingCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    List<TradeNegativeBalanceFundingCost> selectByExample(TradeNegativeBalanceFundingCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    TradeNegativeBalanceFundingCost selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeNegativeBalanceFundingCost record, @Param("example") TradeNegativeBalanceFundingCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeNegativeBalanceFundingCost record, @Param("example") TradeNegativeBalanceFundingCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeNegativeBalanceFundingCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeNegativeBalanceFundingCost record);
}