package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeSpotOrderModification;
import com.google.backend.trading.dao.model.TradeSpotOrderModificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeSpotOrderModificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    long countByExample(TradeSpotOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int deleteByExample(TradeSpotOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int insert(TradeSpotOrderModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int insertSelective(TradeSpotOrderModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    List<TradeSpotOrderModification> selectByExample(TradeSpotOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    TradeSpotOrderModification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeSpotOrderModification record, @Param("example") TradeSpotOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeSpotOrderModification record, @Param("example") TradeSpotOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeSpotOrderModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeSpotOrderModification record);
}