package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeSpotOrder;
import com.google.backend.trading.dao.model.TradeSpotOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeSpotOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    long countByExample(TradeSpotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int deleteByExample(TradeSpotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int insert(TradeSpotOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int insertSelective(TradeSpotOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    List<TradeSpotOrder> selectByExample(TradeSpotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    TradeSpotOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeSpotOrder record, @Param("example") TradeSpotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeSpotOrder record, @Param("example") TradeSpotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeSpotOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeSpotOrder record);
}