package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeFundingRate;
import com.google.backend.trading.dao.model.TradeFundingRateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeFundingRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    long countByExample(TradeFundingRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int deleteByExample(TradeFundingRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int insert(TradeFundingRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int insertSelective(TradeFundingRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    List<TradeFundingRate> selectByExample(TradeFundingRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    TradeFundingRate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeFundingRate record, @Param("example") TradeFundingRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeFundingRate record, @Param("example") TradeFundingRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeFundingRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_rate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeFundingRate record);
}