package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradePosition;
import com.google.backend.trading.dao.model.TradePositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradePositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    long countByExample(TradePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int deleteByExample(TradePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int insert(TradePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int insertSelective(TradePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    List<TradePosition> selectByExample(TradePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    TradePosition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradePosition record, @Param("example") TradePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradePosition record, @Param("example") TradePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradePosition record);
}