package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeSwapOrder;
import com.google.backend.trading.dao.model.TradeSwapOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeSwapOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    long countByExample(TradeSwapOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int deleteByExample(TradeSwapOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int insert(TradeSwapOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int insertSelective(TradeSwapOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    List<TradeSwapOrder> selectByExample(TradeSwapOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    TradeSwapOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeSwapOrder record, @Param("example") TradeSwapOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeSwapOrder record, @Param("example") TradeSwapOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeSwapOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeSwapOrder record);
}