package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradePositionLimitUser;
import com.google.backend.trading.dao.model.TradePositionLimitUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DefaultTradePositionLimitUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    long countByExample(TradePositionLimitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int deleteByExample(TradePositionLimitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int insert(TradePositionLimitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int insertSelective(TradePositionLimitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    List<TradePositionLimitUser> selectByExample(TradePositionLimitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    TradePositionLimitUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradePositionLimitUser record, @Param("example") TradePositionLimitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradePositionLimitUser record, @Param("example") TradePositionLimitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradePositionLimitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position_limit_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradePositionLimitUser record);
}