package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeFundingDisable;
import com.google.backend.trading.dao.model.TradeFundingDisableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeFundingDisableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    long countByExample(TradeFundingDisableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int deleteByExample(TradeFundingDisableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int insert(TradeFundingDisable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int insertSelective(TradeFundingDisable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    List<TradeFundingDisable> selectByExample(TradeFundingDisableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    TradeFundingDisable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeFundingDisable record, @Param("example") TradeFundingDisableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeFundingDisable record, @Param("example") TradeFundingDisableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeFundingDisable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_funding_disable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeFundingDisable record);
}