package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeSpotMarginMiddleOrder;
import com.google.backend.trading.dao.model.TradeSpotMarginMiddleOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeSpotMarginMiddleOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    long countByExample(TradeSpotMarginMiddleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int deleteByExample(TradeSpotMarginMiddleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int insert(TradeSpotMarginMiddleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int insertSelective(TradeSpotMarginMiddleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    List<TradeSpotMarginMiddleOrder> selectByExample(TradeSpotMarginMiddleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    TradeSpotMarginMiddleOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeSpotMarginMiddleOrder record, @Param("example") TradeSpotMarginMiddleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeSpotMarginMiddleOrder record, @Param("example") TradeSpotMarginMiddleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeSpotMarginMiddleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_margin_middle_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeSpotMarginMiddleOrder record);
}