package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeFeeUserConfig;
import com.google.backend.trading.dao.model.TradeFeeUserConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeFeeUserConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    long countByExample(TradeFeeUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int deleteByExample(TradeFeeUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int insert(TradeFeeUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int insertSelective(TradeFeeUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    List<TradeFeeUserConfig> selectByExample(TradeFeeUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    TradeFeeUserConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeFeeUserConfig record, @Param("example") TradeFeeUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeFeeUserConfig record, @Param("example") TradeFeeUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeFeeUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_user_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeFeeUserConfig record);
}