package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeFeeDefaultConfig;
import com.google.backend.trading.dao.model.TradeFeeDefaultConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeFeeDefaultConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    long countByExample(TradeFeeDefaultConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int deleteByExample(TradeFeeDefaultConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int insert(TradeFeeDefaultConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int insertSelective(TradeFeeDefaultConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    List<TradeFeeDefaultConfig> selectByExample(TradeFeeDefaultConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    TradeFeeDefaultConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeFeeDefaultConfig record, @Param("example") TradeFeeDefaultConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeFeeDefaultConfig record, @Param("example") TradeFeeDefaultConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeFeeDefaultConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_default_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeFeeDefaultConfig record);
}