package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeUserMarketFavorite;
import com.google.backend.trading.dao.model.TradeUserMarketFavoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeUserMarketFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    long countByExample(TradeUserMarketFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int deleteByExample(TradeUserMarketFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int insert(TradeUserMarketFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int insertSelective(TradeUserMarketFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    List<TradeUserMarketFavorite> selectByExample(TradeUserMarketFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    TradeUserMarketFavorite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeUserMarketFavorite record, @Param("example") TradeUserMarketFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeUserMarketFavorite record, @Param("example") TradeUserMarketFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeUserMarketFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeUserMarketFavorite record);
}