package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeMarginOrderModification;
import com.google.backend.trading.dao.model.TradeMarginOrderModificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeMarginOrderModificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    long countByExample(TradeMarginOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int deleteByExample(TradeMarginOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int insert(TradeMarginOrderModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int insertSelective(TradeMarginOrderModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    List<TradeMarginOrderModification> selectByExample(TradeMarginOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    TradeMarginOrderModification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeMarginOrderModification record, @Param("example") TradeMarginOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeMarginOrderModification record, @Param("example") TradeMarginOrderModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeMarginOrderModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_margin_order_modification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeMarginOrderModification record);
}