package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeTransaction;
import com.google.backend.trading.dao.model.TradeTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    long countByExample(TradeTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int deleteByExample(TradeTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int insert(TradeTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int insertSelective(TradeTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    List<TradeTransaction> selectByExample(TradeTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    TradeTransaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeTransaction record, @Param("example") TradeTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeTransaction record, @Param("example") TradeTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeTransaction record);
}