package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeUserTradeSetting;
import com.google.backend.trading.dao.model.TradeUserTradeSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeUserTradeSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    long countByExample(TradeUserTradeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int deleteByExample(TradeUserTradeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int insert(TradeUserTradeSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int insertSelective(TradeUserTradeSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    List<TradeUserTradeSetting> selectByExample(TradeUserTradeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    TradeUserTradeSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeUserTradeSetting record, @Param("example") TradeUserTradeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeUserTradeSetting record, @Param("example") TradeUserTradeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeUserTradeSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeUserTradeSetting record);
}