package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeTransactionAmount;
import com.google.backend.trading.dao.model.TradeTransactionAmountExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DefaultTradeTransactionAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    long countByExample(TradeTransactionAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int deleteByExample(TradeTransactionAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int insert(TradeTransactionAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int insertSelective(TradeTransactionAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    List<TradeTransactionAmount> selectByExample(TradeTransactionAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    TradeTransactionAmount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeTransactionAmount record, @Param("example") TradeTransactionAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeTransactionAmount record, @Param("example") TradeTransactionAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeTransactionAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transaction_amount
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeTransactionAmount record);
}