package com.google.backend.trading.dao.mapper;

import com.google.backend.trading.dao.model.TradeUserMarketFavoriteLite;
import com.google.backend.trading.dao.model.TradeUserMarketFavoriteLiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultTradeUserMarketFavoriteLiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    long countByExample(TradeUserMarketFavoriteLiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int deleteByExample(TradeUserMarketFavoriteLiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int insert(TradeUserMarketFavoriteLite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int insertSelective(TradeUserMarketFavoriteLite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    List<TradeUserMarketFavoriteLite> selectByExample(TradeUserMarketFavoriteLiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    TradeUserMarketFavoriteLite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeUserMarketFavoriteLite record, @Param("example") TradeUserMarketFavoriteLiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeUserMarketFavoriteLite record, @Param("example") TradeUserMarketFavoriteLiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeUserMarketFavoriteLite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_market_favorite_lite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeUserMarketFavoriteLite record);
}