package com.google.backend.trading.model.internal.amp;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @author adam.wang
 * @date 2021/11/18 17:13
 */
@Data
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
@ApiModel(value = "APM仓位资金返回对象")
public class AmpPositionFundRes {


    /**
     * Database Column Remarks:
     *   uuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.uuid
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "uuid",value = "流水ID", example = "57e1a41a-584a-4774-bb34-217a385c4ec3")
    private String uuid;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.uid
     *
     * @mbg.generated
     */
    @NotBlank
    @ApiModelProperty(name = "uid",value = "用户编码", required = true, example = "57e1a41a-584a-4774-bb34-217a385c4ec3")
    private String uid;

    /**
     * Database Column Remarks:
     *   pending   completed
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.status
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "仓位状态 PENDING（等待状态） COMPLETED（已完成状态），ALL不传参数", example = "PENDING")
    private String status;

    /**
     * Database Column Remarks:
     *   资金费率的费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.funding_cost
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "funding_cost",value = "资金费率的费用", example = "3.2")
    private BigDecimal fundingCost;

    /**
     * Database Column Remarks:
     *   仓位id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.position_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "position_id",value = "仓位ID", example = "57e1a41a-584a-4774-bb34-217a385c4ec3")
    private String positionId;

    /**
     * Database Column Remarks:
     *   仓位币对
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.symbol
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "币对", example = "BTC_USD")
    private String symbol;


    /**
     * Database Column Remarks:
     *   用户借出利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.lend
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "用户借出利率（小数）", example = "0.002")
    private BigDecimal lend;

    /**
     * Database Column Remarks:
     *   用户借入利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.borrow
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "用户借入利率（小数）", example = "0.002")
    private BigDecimal borrow;

    /**
     * Database Column Remarks:
     *   收取资金费率轮次的时间点（毫秒时间戳）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.round
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "费率计算周期(收取资金费率轮次的时间点（毫秒时间戳）)", example = "1637438400000")
    private Long round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.ctime
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "创建时间", example = "")
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position_funding_cost.mtime
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "修改时间", example = "")
    private Date mtime;

    @ApiModelProperty(value = "币种", example = "USD")
    private String coin = "USD";

    @ApiModelProperty(value = "仓位方向  BUY 买，SELL卖",example = "BUY")
    private String direction;

    @ApiModelProperty(value = "Position size of Settlement",example = "1")
    private BigDecimal positionSize;
    @ApiModelProperty(value = "Settle Price（USD） ",example = "1")
    private BigDecimal settlePrice;
}
