spring:
  data:
    mongodb:
      uri: mongodb://useradmin:google#&*asc@172.24.247.128:27017/google?authSource=google
  datasource:
    url: jdbc:postgresql://aws-jp-google-allmodule-pg-nonprod.ckcvjkzxh8bd.ap-northeast-1.rds.amazonaws.com:5432/trade_dev?prepareThreshold=0
    username: trade_readwrite_dev
    password: N73UDa#U7PVp2Z)VJl9gVu
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5  # 初始化时建立物理连接的个数
      max-active: 10 # 最大连接池数量
      max-wait: 5000 # 最大等待ms
      min-idle: 5  # 最小连接池数量
      use-unfair-lock: true
  redis:
    host: master.aws-jp-google-allmodule-redis-nonprod.8loycm.apne1.cache.amazonaws.com
    port: 6379
    password: zaBuQ#AAuDyT)ybLxR3IoB
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5
        time-between-eviction-runs: 60000
    database: 0
    timeout: 5000
    ssl: true
  kafka:
    bootstrap-servers: b-2.google-alltest.7n9wg1.c2.kafka.ap-northeast-1.amazonaws.com:9096,b-3.google-alltest.7n9wg1.c2.kafka.ap-northeast-1.amazonaws.com:9096,b-1.google-alltest.7n9wg1.c2.kafka.ap-northeast-1.amazonaws.com:9096
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: google-google-trade-service-group-dev
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username=mskuser password=mskuser-wkp1gGGnZR;
        mechanism: SCRAM-SHA-512
      security:
        protocol: SASL_SSL
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
#资金模块地址
asset:
  host: https://internal-gateway-dev.googleainsider.com/asset
#风控模块地址
risk:
  host: https://internal-gateway-dev.googleainsider.com/risk-control
  topic:
    reducePosition: google-google-trading-reduce-position-dev
    cancelOrder: google-google-trading-cancel-order-dev
    liquidSpot: google-google-trading-liquid-spot-dev
    liquidBalance: google-google-trading-liquid-balance-dev
    user-setting: google-google-trading-user-setting-dev
    position-open: google-google-trading-position-open-dev
    position-change: google-google-trading-position-change-dev
#发单模块
pdt:
  server:
    host: https://internal-gateway-dev.googleainsider.com
  redis:
    host: master.aws-jp-google-crex-redis-dev.8loycm.apne1.cache.amazonaws.com
    port: 6379
    password: 0SPXEZgMfUOx#xd6wY0EH
    timeout: 6000
    database: 0
    ssl: true
common-config:
  host: https://internal-gateway-dev.googleainsider.com/common-config
kline:
  host: https://internal-gateway-dev.googleainsider.com/kline
kline-coingecko:
  host: https://kline-api.googleainsider.com
#用户量模块
user-center:
  host: https://internal-gateway-dev.googleainsider.com/user-center
# ClubServer
club:
  host: https://internal-gateway-dev.googleainsider.com/club
alarm:
  host: https://alarm.googleainsider.com/server/alarm_server
kafka:
  topic:
    ws-push: "google-google-ws-event-dev"
    usertouch-push: google-google-usercenter-usertouch-dev
    funding-push: google-google-referral-funding-trading-dev
    aceup-tradefee-config-consumer: google-google-aceup-trade-fee-config-dev
    buy-crypt-result: google-google-trading-buycrypto-convertion-dev
    aip-swap-place-order-consumer: google-google-trade-swapplaceorder-dev
    aip-swap-place-order-push: google-google-aip-swapplaceorder-dev
    algo-transaction-statistics-consumer: google-google-trading-transaction-statistics-dev
place:
  max-num: 500
trade:
  otc-booking:
    uid-arr:
      - "616289d4d4b1a6d195d6f288"
  sensors:
    log-path: ./log/sensordata
  margin:
    ip-compliance: false

app-migrate:
  pgsql:
    url: jdbc:postgresql://172.24.247.129:5432/google
    username: readwrite
    password: .whn_E2D5*)z.h
xxl:
  job.admin.addresses: https://xxljob-admin-dev.googleainsider.com/xxl-job-admin
  job.accessToken:
  job.executor:
    appname: trading-service-task-dev
    address:
    ip: google-trading-svc.google-dev.svc
    port: 9999
    logpath: ./log/xxl-job/
    logretentiondays: 30
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl