package com.google.backend.trading.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradePositionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public TradePositionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNull() {
            addCriterion("symbol is null");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNotNull() {
            addCriterion("symbol is not null");
            return (Criteria) this;
        }

        public Criteria andSymbolEqualTo(String value) {
            addCriterion("symbol =", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotEqualTo(String value) {
            addCriterion("symbol <>", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThan(String value) {
            addCriterion("symbol >", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("symbol >=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThan(String value) {
            addCriterion("symbol <", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThanOrEqualTo(String value) {
            addCriterion("symbol <=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLike(String value) {
            addCriterion("symbol like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotLike(String value) {
            addCriterion("symbol not like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolIn(List<String> values) {
            addCriterion("symbol in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotIn(List<String> values) {
            addCriterion("symbol not in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolBetween(String value1, String value2) {
            addCriterion("symbol between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotBetween(String value1, String value2) {
            addCriterion("symbol not between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(String value) {
            addCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(String value) {
            addCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(String value) {
            addCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(String value) {
            addCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(String value) {
            addCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLike(String value) {
            addCriterion("direction like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotLike(String value) {
            addCriterion("direction not like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<String> values) {
            addCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<String> values) {
            addCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(String value1, String value2) {
            addCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(String value1, String value2) {
            addCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(BigDecimal value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(BigDecimal value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(BigDecimal value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(BigDecimal value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<BigDecimal> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<BigDecimal> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andAutoSettleIsNull() {
            addCriterion("auto_settle is null");
            return (Criteria) this;
        }

        public Criteria andAutoSettleIsNotNull() {
            addCriterion("auto_settle is not null");
            return (Criteria) this;
        }

        public Criteria andAutoSettleEqualTo(Boolean value) {
            addCriterion("auto_settle =", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleNotEqualTo(Boolean value) {
            addCriterion("auto_settle <>", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleGreaterThan(Boolean value) {
            addCriterion("auto_settle >", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("auto_settle >=", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleLessThan(Boolean value) {
            addCriterion("auto_settle <", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleLessThanOrEqualTo(Boolean value) {
            addCriterion("auto_settle <=", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleIn(List<Boolean> values) {
            addCriterion("auto_settle in", values, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleNotIn(List<Boolean> values) {
            addCriterion("auto_settle not in", values, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_settle between", value1, value2, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_settle not between", value1, value2, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceIsNull() {
            addCriterion("stop_loss_price is null");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceIsNotNull() {
            addCriterion("stop_loss_price is not null");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceEqualTo(BigDecimal value) {
            addCriterion("stop_loss_price =", value, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceNotEqualTo(BigDecimal value) {
            addCriterion("stop_loss_price <>", value, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceGreaterThan(BigDecimal value) {
            addCriterion("stop_loss_price >", value, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stop_loss_price >=", value, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceLessThan(BigDecimal value) {
            addCriterion("stop_loss_price <", value, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stop_loss_price <=", value, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceIn(List<BigDecimal> values) {
            addCriterion("stop_loss_price in", values, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceNotIn(List<BigDecimal> values) {
            addCriterion("stop_loss_price not in", values, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stop_loss_price between", value1, value2, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stop_loss_price not between", value1, value2, "stopLossPrice");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageIsNull() {
            addCriterion("stop_loss_percentage is null");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageIsNotNull() {
            addCriterion("stop_loss_percentage is not null");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageEqualTo(BigDecimal value) {
            addCriterion("stop_loss_percentage =", value, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageNotEqualTo(BigDecimal value) {
            addCriterion("stop_loss_percentage <>", value, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageGreaterThan(BigDecimal value) {
            addCriterion("stop_loss_percentage >", value, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stop_loss_percentage >=", value, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageLessThan(BigDecimal value) {
            addCriterion("stop_loss_percentage <", value, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stop_loss_percentage <=", value, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageIn(List<BigDecimal> values) {
            addCriterion("stop_loss_percentage in", values, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageNotIn(List<BigDecimal> values) {
            addCriterion("stop_loss_percentage not in", values, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stop_loss_percentage between", value1, value2, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andStopLossPercentageNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stop_loss_percentage not between", value1, value2, "stopLossPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceIsNull() {
            addCriterion("take_profit_price is null");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceIsNotNull() {
            addCriterion("take_profit_price is not null");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceEqualTo(BigDecimal value) {
            addCriterion("take_profit_price =", value, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceNotEqualTo(BigDecimal value) {
            addCriterion("take_profit_price <>", value, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceGreaterThan(BigDecimal value) {
            addCriterion("take_profit_price >", value, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("take_profit_price >=", value, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceLessThan(BigDecimal value) {
            addCriterion("take_profit_price <", value, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("take_profit_price <=", value, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceIn(List<BigDecimal> values) {
            addCriterion("take_profit_price in", values, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceNotIn(List<BigDecimal> values) {
            addCriterion("take_profit_price not in", values, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("take_profit_price between", value1, value2, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("take_profit_price not between", value1, value2, "takeProfitPrice");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageIsNull() {
            addCriterion("take_profit_percentage is null");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageIsNotNull() {
            addCriterion("take_profit_percentage is not null");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageEqualTo(BigDecimal value) {
            addCriterion("take_profit_percentage =", value, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageNotEqualTo(BigDecimal value) {
            addCriterion("take_profit_percentage <>", value, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageGreaterThan(BigDecimal value) {
            addCriterion("take_profit_percentage >", value, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("take_profit_percentage >=", value, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageLessThan(BigDecimal value) {
            addCriterion("take_profit_percentage <", value, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageLessThanOrEqualTo(BigDecimal value) {
            addCriterion("take_profit_percentage <=", value, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageIn(List<BigDecimal> values) {
            addCriterion("take_profit_percentage in", values, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageNotIn(List<BigDecimal> values) {
            addCriterion("take_profit_percentage not in", values, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("take_profit_percentage between", value1, value2, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andTakeProfitPercentageNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("take_profit_percentage not between", value1, value2, "takeProfitPercentage");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityIsNull() {
            addCriterion("max_quantity is null");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityIsNotNull() {
            addCriterion("max_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityEqualTo(BigDecimal value) {
            addCriterion("max_quantity =", value, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityNotEqualTo(BigDecimal value) {
            addCriterion("max_quantity <>", value, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityGreaterThan(BigDecimal value) {
            addCriterion("max_quantity >", value, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("max_quantity >=", value, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityLessThan(BigDecimal value) {
            addCriterion("max_quantity <", value, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("max_quantity <=", value, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityIn(List<BigDecimal> values) {
            addCriterion("max_quantity in", values, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityNotIn(List<BigDecimal> values) {
            addCriterion("max_quantity not in", values, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_quantity between", value1, value2, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andMaxQuantityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_quantity not between", value1, value2, "maxQuantity");
            return (Criteria) this;
        }

        public Criteria andPnlIsNull() {
            addCriterion("pnl is null");
            return (Criteria) this;
        }

        public Criteria andPnlIsNotNull() {
            addCriterion("pnl is not null");
            return (Criteria) this;
        }

        public Criteria andPnlEqualTo(BigDecimal value) {
            addCriterion("pnl =", value, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlNotEqualTo(BigDecimal value) {
            addCriterion("pnl <>", value, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlGreaterThan(BigDecimal value) {
            addCriterion("pnl >", value, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pnl >=", value, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlLessThan(BigDecimal value) {
            addCriterion("pnl <", value, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pnl <=", value, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlIn(List<BigDecimal> values) {
            addCriterion("pnl in", values, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlNotIn(List<BigDecimal> values) {
            addCriterion("pnl not in", values, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pnl between", value1, value2, "pnl");
            return (Criteria) this;
        }

        public Criteria andPnlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pnl not between", value1, value2, "pnl");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_position
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}