package com.google.backend.trading.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 * booking账户名单
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_user_booking_list
 */
public class TradeUserBookingList implements Serializable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_booking_list.id
	 *
	 * @mbg.generated
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_booking_list.uid
	 *
	 * @mbg.generated
	 */
	private String uid;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_booking_list.ctime
	 *
	 * @mbg.generated
	 */
	private Date ctime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_booking_list.mtime
	 *
	 * @mbg.generated
	 */
	private Date mtime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_booking_list.remark
	 *
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table trade_user_booking_list
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column trade_user_booking_list.id
	 *
	 * @return the value of trade_user_booking_list.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column trade_user_booking_list.id
	 *
	 * @param id the value for trade_user_booking_list.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column trade_user_booking_list.uid
	 *
	 * @return the value of trade_user_booking_list.uid
	 * @mbg.generated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column trade_user_booking_list.uid
	 *
	 * @param uid the value for trade_user_booking_list.uid
	 * @mbg.generated
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column trade_user_booking_list.ctime
	 *
	 * @return the value of trade_user_booking_list.ctime
	 * @mbg.generated
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column trade_user_booking_list.ctime
	 *
	 * @param ctime the value for trade_user_booking_list.ctime
	 * @mbg.generated
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column trade_user_booking_list.mtime
	 *
	 * @return the value of trade_user_booking_list.mtime
	 * @mbg.generated
	 */
	public Date getMtime() {
		return mtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column trade_user_booking_list.mtime
	 *
	 * @param mtime the value for trade_user_booking_list.mtime
	 * @mbg.generated
	 */
	public void setMtime(Date mtime) {
		this.mtime = mtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column trade_user_booking_list.remark
	 *
	 * @return the value of trade_user_booking_list.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column trade_user_booking_list.remark
	 *
	 * @param remark the value for trade_user_booking_list.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table trade_user_booking_list
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", uid=").append(uid);
		sb.append(", ctime=").append(ctime);
		sb.append(", mtime=").append(mtime);
		sb.append(", remark=").append(remark);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}