package com.google.backend.trading.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   杠杆订单修改记录表(包含有修改过的订单下单记录，按ctime顺序，第一条记录为订单下单记录)
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_spot_order_modification
 */
public class TradeSpotOrderModification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   修改委托数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.quantity
     *
     * @mbg.generated
     */
    private BigDecimal quantity;

    /**
     * Database Column Remarks:
     *   修改锁定数额（维持订单成交的锁定金额）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.lock_amount
     *
     * @mbg.generated
     */
    private BigDecimal lockAmount;

    /**
     * Database Column Remarks:
     *   for limit, stop_limit 修改委托价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   for stop_limit, stop_market 修改触发价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.trigger_price
     *
     * @mbg.generated
     */
    private BigDecimal triggerPrice;

    /**
     * Database Column Remarks:
     *   for stop_limit, stop_market，值为 greater less，意为大于/小于触发价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.trigger_compare
     *
     * @mbg.generated
     */
    private String triggerCompare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     * Database Column Remarks:
     *   订单修改时状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.current_status
     *
     * @mbg.generated
     */
    private String currentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order_modification.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.id
     *
     * @return the value of trade_spot_order_modification.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.id
     *
     * @param id the value for trade_spot_order_modification.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.uuid
     *
     * @return the value of trade_spot_order_modification.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.uuid
     *
     * @param uuid the value for trade_spot_order_modification.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.order_id
     *
     * @return the value of trade_spot_order_modification.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.order_id
     *
     * @param orderId the value for trade_spot_order_modification.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.quantity
     *
     * @return the value of trade_spot_order_modification.quantity
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.quantity
     *
     * @param quantity the value for trade_spot_order_modification.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.lock_amount
     *
     * @return the value of trade_spot_order_modification.lock_amount
     *
     * @mbg.generated
     */
    public BigDecimal getLockAmount() {
        return lockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.lock_amount
     *
     * @param lockAmount the value for trade_spot_order_modification.lock_amount
     *
     * @mbg.generated
     */
    public void setLockAmount(BigDecimal lockAmount) {
        this.lockAmount = lockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.price
     *
     * @return the value of trade_spot_order_modification.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.price
     *
     * @param price the value for trade_spot_order_modification.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.trigger_price
     *
     * @return the value of trade_spot_order_modification.trigger_price
     *
     * @mbg.generated
     */
    public BigDecimal getTriggerPrice() {
        return triggerPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.trigger_price
     *
     * @param triggerPrice the value for trade_spot_order_modification.trigger_price
     *
     * @mbg.generated
     */
    public void setTriggerPrice(BigDecimal triggerPrice) {
        this.triggerPrice = triggerPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.trigger_compare
     *
     * @return the value of trade_spot_order_modification.trigger_compare
     *
     * @mbg.generated
     */
    public String getTriggerCompare() {
        return triggerCompare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.trigger_compare
     *
     * @param triggerCompare the value for trade_spot_order_modification.trigger_compare
     *
     * @mbg.generated
     */
    public void setTriggerCompare(String triggerCompare) {
        this.triggerCompare = triggerCompare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.notes
     *
     * @return the value of trade_spot_order_modification.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.notes
     *
     * @param notes the value for trade_spot_order_modification.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.current_status
     *
     * @return the value of trade_spot_order_modification.current_status
     *
     * @mbg.generated
     */
    public String getCurrentStatus() {
        return currentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.current_status
     *
     * @param currentStatus the value for trade_spot_order_modification.current_status
     *
     * @mbg.generated
     */
    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order_modification.ctime
     *
     * @return the value of trade_spot_order_modification.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order_modification.ctime
     *
     * @param ctime the value for trade_spot_order_modification.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order_modification
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", orderId=").append(orderId);
        sb.append(", quantity=").append(quantity);
        sb.append(", lockAmount=").append(lockAmount);
        sb.append(", price=").append(price);
        sb.append(", triggerPrice=").append(triggerPrice);
        sb.append(", triggerCompare=").append(triggerCompare);
        sb.append(", notes=").append(notes);
        sb.append(", currentStatus=").append(currentStatus);
        sb.append(", ctime=").append(ctime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}