package com.google.backend.trading.dao.model;

import java.io.Serializable;
import org.postgresql.util.PGobject;

/**
 * Database Table Remarks:
 *   用户页面设置（给web端使用）
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_user_page_setting
 */
public class TradeUserPageSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_user_page_setting.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_user_page_setting.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   行情卡片设置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_user_page_setting.price_card
     *
     * @mbg.generated
     */
    private PGobject priceCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_user_page_setting
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_page_setting.id
     *
     * @return the value of trade_user_page_setting.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_page_setting.id
     *
     * @param id the value for trade_user_page_setting.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_page_setting.uid
     *
     * @return the value of trade_user_page_setting.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_page_setting.uid
     *
     * @param uid the value for trade_user_page_setting.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_page_setting.price_card
     *
     * @return the value of trade_user_page_setting.price_card
     *
     * @mbg.generated
     */
    public PGobject getPriceCard() {
        return priceCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_page_setting.price_card
     *
     * @param priceCard the value for trade_user_page_setting.price_card
     *
     * @mbg.generated
     */
    public void setPriceCard(PGobject priceCard) {
        this.priceCard = priceCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_page_setting
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", priceCard=").append(priceCard);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}