package com.google.backend.trading.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradeUserTradeSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public TradeUserTradeSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andLeverageIsNull() {
            addCriterion("leverage is null");
            return (Criteria) this;
        }

        public Criteria andLeverageIsNotNull() {
            addCriterion("leverage is not null");
            return (Criteria) this;
        }

        public Criteria andLeverageEqualTo(BigDecimal value) {
            addCriterion("leverage =", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageNotEqualTo(BigDecimal value) {
            addCriterion("leverage <>", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageGreaterThan(BigDecimal value) {
            addCriterion("leverage >", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("leverage >=", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageLessThan(BigDecimal value) {
            addCriterion("leverage <", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageLessThanOrEqualTo(BigDecimal value) {
            addCriterion("leverage <=", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageIn(List<BigDecimal> values) {
            addCriterion("leverage in", values, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageNotIn(List<BigDecimal> values) {
            addCriterion("leverage not in", values, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leverage between", value1, value2, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leverage not between", value1, value2, "leverage");
            return (Criteria) this;
        }

        public Criteria andMaxLossIsNull() {
            addCriterion("max_loss is null");
            return (Criteria) this;
        }

        public Criteria andMaxLossIsNotNull() {
            addCriterion("max_loss is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLossEqualTo(BigDecimal value) {
            addCriterion("max_loss =", value, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossNotEqualTo(BigDecimal value) {
            addCriterion("max_loss <>", value, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossGreaterThan(BigDecimal value) {
            addCriterion("max_loss >", value, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("max_loss >=", value, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossLessThan(BigDecimal value) {
            addCriterion("max_loss <", value, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossLessThanOrEqualTo(BigDecimal value) {
            addCriterion("max_loss <=", value, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossIn(List<BigDecimal> values) {
            addCriterion("max_loss in", values, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossNotIn(List<BigDecimal> values) {
            addCriterion("max_loss not in", values, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_loss between", value1, value2, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andMaxLossNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_loss not between", value1, value2, "maxLoss");
            return (Criteria) this;
        }

        public Criteria andTakeProfitIsNull() {
            addCriterion("take_profit is null");
            return (Criteria) this;
        }

        public Criteria andTakeProfitIsNotNull() {
            addCriterion("take_profit is not null");
            return (Criteria) this;
        }

        public Criteria andTakeProfitEqualTo(BigDecimal value) {
            addCriterion("take_profit =", value, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitNotEqualTo(BigDecimal value) {
            addCriterion("take_profit <>", value, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitGreaterThan(BigDecimal value) {
            addCriterion("take_profit >", value, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("take_profit >=", value, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitLessThan(BigDecimal value) {
            addCriterion("take_profit <", value, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("take_profit <=", value, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitIn(List<BigDecimal> values) {
            addCriterion("take_profit in", values, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitNotIn(List<BigDecimal> values) {
            addCriterion("take_profit not in", values, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("take_profit between", value1, value2, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andTakeProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("take_profit not between", value1, value2, "takeProfit");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeIsNull() {
            addCriterion("earn_pledge is null");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeIsNotNull() {
            addCriterion("earn_pledge is not null");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeEqualTo(Boolean value) {
            addCriterion("earn_pledge =", value, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeNotEqualTo(Boolean value) {
            addCriterion("earn_pledge <>", value, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeGreaterThan(Boolean value) {
            addCriterion("earn_pledge >", value, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("earn_pledge >=", value, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeLessThan(Boolean value) {
            addCriterion("earn_pledge <", value, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeLessThanOrEqualTo(Boolean value) {
            addCriterion("earn_pledge <=", value, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeIn(List<Boolean> values) {
            addCriterion("earn_pledge in", values, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeNotIn(List<Boolean> values) {
            addCriterion("earn_pledge not in", values, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeBetween(Boolean value1, Boolean value2) {
            addCriterion("earn_pledge between", value1, value2, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andEarnPledgeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("earn_pledge not between", value1, value2, "earnPledge");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinIsNull() {
            addCriterion("default_coin is null");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinIsNotNull() {
            addCriterion("default_coin is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinEqualTo(String value) {
            addCriterion("default_coin =", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinNotEqualTo(String value) {
            addCriterion("default_coin <>", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinGreaterThan(String value) {
            addCriterion("default_coin >", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinGreaterThanOrEqualTo(String value) {
            addCriterion("default_coin >=", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinLessThan(String value) {
            addCriterion("default_coin <", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinLessThanOrEqualTo(String value) {
            addCriterion("default_coin <=", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinLike(String value) {
            addCriterion("default_coin like", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinNotLike(String value) {
            addCriterion("default_coin not like", value, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinIn(List<String> values) {
            addCriterion("default_coin in", values, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinNotIn(List<String> values) {
            addCriterion("default_coin not in", values, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinBetween(String value1, String value2) {
            addCriterion("default_coin between", value1, value2, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andDefaultCoinNotBetween(String value1, String value2) {
            addCriterion("default_coin not between", value1, value2, "defaultCoin");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdIsNull() {
            addCriterion("settle_time_zone_id is null");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdIsNotNull() {
            addCriterion("settle_time_zone_id is not null");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdEqualTo(String value) {
            addCriterion("settle_time_zone_id =", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdNotEqualTo(String value) {
            addCriterion("settle_time_zone_id <>", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdGreaterThan(String value) {
            addCriterion("settle_time_zone_id >", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdGreaterThanOrEqualTo(String value) {
            addCriterion("settle_time_zone_id >=", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdLessThan(String value) {
            addCriterion("settle_time_zone_id <", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdLessThanOrEqualTo(String value) {
            addCriterion("settle_time_zone_id <=", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdLike(String value) {
            addCriterion("settle_time_zone_id like", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdNotLike(String value) {
            addCriterion("settle_time_zone_id not like", value, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdIn(List<String> values) {
            addCriterion("settle_time_zone_id in", values, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdNotIn(List<String> values) {
            addCriterion("settle_time_zone_id not in", values, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdBetween(String value1, String value2) {
            addCriterion("settle_time_zone_id between", value1, value2, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andSettleTimeZoneIdNotBetween(String value1, String value2) {
            addCriterion("settle_time_zone_id not between", value1, value2, "settleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andAutoSettleIsNull() {
            addCriterion("auto_settle is null");
            return (Criteria) this;
        }

        public Criteria andAutoSettleIsNotNull() {
            addCriterion("auto_settle is not null");
            return (Criteria) this;
        }

        public Criteria andAutoSettleEqualTo(Boolean value) {
            addCriterion("auto_settle =", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleNotEqualTo(Boolean value) {
            addCriterion("auto_settle <>", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleGreaterThan(Boolean value) {
            addCriterion("auto_settle >", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("auto_settle >=", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleLessThan(Boolean value) {
            addCriterion("auto_settle <", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleLessThanOrEqualTo(Boolean value) {
            addCriterion("auto_settle <=", value, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleIn(List<Boolean> values) {
            addCriterion("auto_settle in", values, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleNotIn(List<Boolean> values) {
            addCriterion("auto_settle not in", values, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_settle between", value1, value2, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoSettleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_settle not between", value1, value2, "autoSettle");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeIsNull() {
            addCriterion("auto_fix_negative is null");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeIsNotNull() {
            addCriterion("auto_fix_negative is not null");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeEqualTo(Boolean value) {
            addCriterion("auto_fix_negative =", value, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeNotEqualTo(Boolean value) {
            addCriterion("auto_fix_negative <>", value, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeGreaterThan(Boolean value) {
            addCriterion("auto_fix_negative >", value, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("auto_fix_negative >=", value, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeLessThan(Boolean value) {
            addCriterion("auto_fix_negative <", value, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeLessThanOrEqualTo(Boolean value) {
            addCriterion("auto_fix_negative <=", value, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeIn(List<Boolean> values) {
            addCriterion("auto_fix_negative in", values, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeNotIn(List<Boolean> values) {
            addCriterion("auto_fix_negative not in", values, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_fix_negative between", value1, value2, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andAutoFixNegativeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_fix_negative not between", value1, value2, "autoFixNegative");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnIsNull() {
            addCriterion("liquid_earn is null");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnIsNotNull() {
            addCriterion("liquid_earn is not null");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnEqualTo(Boolean value) {
            addCriterion("liquid_earn =", value, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnNotEqualTo(Boolean value) {
            addCriterion("liquid_earn <>", value, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnGreaterThan(Boolean value) {
            addCriterion("liquid_earn >", value, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnGreaterThanOrEqualTo(Boolean value) {
            addCriterion("liquid_earn >=", value, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnLessThan(Boolean value) {
            addCriterion("liquid_earn <", value, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnLessThanOrEqualTo(Boolean value) {
            addCriterion("liquid_earn <=", value, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnIn(List<Boolean> values) {
            addCriterion("liquid_earn in", values, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnNotIn(List<Boolean> values) {
            addCriterion("liquid_earn not in", values, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnBetween(Boolean value1, Boolean value2) {
            addCriterion("liquid_earn between", value1, value2, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andLiquidEarnNotBetween(Boolean value1, Boolean value2) {
            addCriterion("liquid_earn not between", value1, value2, "liquidEarn");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationIsNull() {
            addCriterion("email_notification is null");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationIsNotNull() {
            addCriterion("email_notification is not null");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationEqualTo(Boolean value) {
            addCriterion("email_notification =", value, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationNotEqualTo(Boolean value) {
            addCriterion("email_notification <>", value, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationGreaterThan(Boolean value) {
            addCriterion("email_notification >", value, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("email_notification >=", value, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationLessThan(Boolean value) {
            addCriterion("email_notification <", value, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationLessThanOrEqualTo(Boolean value) {
            addCriterion("email_notification <=", value, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationIn(List<Boolean> values) {
            addCriterion("email_notification in", values, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationNotIn(List<Boolean> values) {
            addCriterion("email_notification not in", values, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationBetween(Boolean value1, Boolean value2) {
            addCriterion("email_notification between", value1, value2, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andEmailNotificationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("email_notification not between", value1, value2, "emailNotification");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderIsNull() {
            addCriterion("reconfirm_order is null");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderIsNotNull() {
            addCriterion("reconfirm_order is not null");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderEqualTo(Boolean value) {
            addCriterion("reconfirm_order =", value, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderNotEqualTo(Boolean value) {
            addCriterion("reconfirm_order <>", value, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderGreaterThan(Boolean value) {
            addCriterion("reconfirm_order >", value, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderGreaterThanOrEqualTo(Boolean value) {
            addCriterion("reconfirm_order >=", value, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderLessThan(Boolean value) {
            addCriterion("reconfirm_order <", value, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderLessThanOrEqualTo(Boolean value) {
            addCriterion("reconfirm_order <=", value, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderIn(List<Boolean> values) {
            addCriterion("reconfirm_order in", values, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderNotIn(List<Boolean> values) {
            addCriterion("reconfirm_order not in", values, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderBetween(Boolean value1, Boolean value2) {
            addCriterion("reconfirm_order between", value1, value2, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andReconfirmOrderNotBetween(Boolean value1, Boolean value2) {
            addCriterion("reconfirm_order not between", value1, value2, "reconfirmOrder");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderIsNull() {
            addCriterion("double_click_place_order is null");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderIsNotNull() {
            addCriterion("double_click_place_order is not null");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderEqualTo(Boolean value) {
            addCriterion("double_click_place_order =", value, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderNotEqualTo(Boolean value) {
            addCriterion("double_click_place_order <>", value, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderGreaterThan(Boolean value) {
            addCriterion("double_click_place_order >", value, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderGreaterThanOrEqualTo(Boolean value) {
            addCriterion("double_click_place_order >=", value, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderLessThan(Boolean value) {
            addCriterion("double_click_place_order <", value, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderLessThanOrEqualTo(Boolean value) {
            addCriterion("double_click_place_order <=", value, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderIn(List<Boolean> values) {
            addCriterion("double_click_place_order in", values, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderNotIn(List<Boolean> values) {
            addCriterion("double_click_place_order not in", values, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderBetween(Boolean value1, Boolean value2) {
            addCriterion("double_click_place_order between", value1, value2, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andDoubleClickPlaceOrderNotBetween(Boolean value1, Boolean value2) {
            addCriterion("double_click_place_order not between", value1, value2, "doubleClickPlaceOrder");
            return (Criteria) this;
        }

        public Criteria andAutoConvertIsNull() {
            addCriterion("auto_convert is null");
            return (Criteria) this;
        }

        public Criteria andAutoConvertIsNotNull() {
            addCriterion("auto_convert is not null");
            return (Criteria) this;
        }

        public Criteria andAutoConvertEqualTo(Boolean value) {
            addCriterion("auto_convert =", value, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertNotEqualTo(Boolean value) {
            addCriterion("auto_convert <>", value, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertGreaterThan(Boolean value) {
            addCriterion("auto_convert >", value, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertGreaterThanOrEqualTo(Boolean value) {
            addCriterion("auto_convert >=", value, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertLessThan(Boolean value) {
            addCriterion("auto_convert <", value, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertLessThanOrEqualTo(Boolean value) {
            addCriterion("auto_convert <=", value, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertIn(List<Boolean> values) {
            addCriterion("auto_convert in", values, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertNotIn(List<Boolean> values) {
            addCriterion("auto_convert not in", values, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_convert between", value1, value2, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andAutoConvertNotBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_convert not between", value1, value2, "autoConvert");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeIsNull() {
            addCriterion("settle_time_next_effective_time is null");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeIsNotNull() {
            addCriterion("settle_time_next_effective_time is not null");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeEqualTo(Date value) {
            addCriterion("settle_time_next_effective_time =", value, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeNotEqualTo(Date value) {
            addCriterion("settle_time_next_effective_time <>", value, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeGreaterThan(Date value) {
            addCriterion("settle_time_next_effective_time >", value, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("settle_time_next_effective_time >=", value, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeLessThan(Date value) {
            addCriterion("settle_time_next_effective_time <", value, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("settle_time_next_effective_time <=", value, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeIn(List<Date> values) {
            addCriterion("settle_time_next_effective_time in", values, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeNotIn(List<Date> values) {
            addCriterion("settle_time_next_effective_time not in", values, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeBetween(Date value1, Date value2) {
            addCriterion("settle_time_next_effective_time between", value1, value2, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andSettleTimeNextEffectiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("settle_time_next_effective_time not between", value1, value2, "settleTimeNextEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdIsNull() {
            addCriterion("last_settle_time_zone_id is null");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdIsNotNull() {
            addCriterion("last_settle_time_zone_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdEqualTo(String value) {
            addCriterion("last_settle_time_zone_id =", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdNotEqualTo(String value) {
            addCriterion("last_settle_time_zone_id <>", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdGreaterThan(String value) {
            addCriterion("last_settle_time_zone_id >", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_settle_time_zone_id >=", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdLessThan(String value) {
            addCriterion("last_settle_time_zone_id <", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdLessThanOrEqualTo(String value) {
            addCriterion("last_settle_time_zone_id <=", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdLike(String value) {
            addCriterion("last_settle_time_zone_id like", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdNotLike(String value) {
            addCriterion("last_settle_time_zone_id not like", value, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdIn(List<String> values) {
            addCriterion("last_settle_time_zone_id in", values, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdNotIn(List<String> values) {
            addCriterion("last_settle_time_zone_id not in", values, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdBetween(String value1, String value2) {
            addCriterion("last_settle_time_zone_id between", value1, value2, "lastSettleTimeZoneId");
            return (Criteria) this;
        }

        public Criteria andLastSettleTimeZoneIdNotBetween(String value1, String value2) {
            addCriterion("last_settle_time_zone_id not between", value1, value2, "lastSettleTimeZoneId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_user_trade_setting
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}