package com.google.backend.trading.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TradeFeeConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public TradeFeeConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateIsNull() {
            addCriterion("spot_fee_rate is null");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateIsNotNull() {
            addCriterion("spot_fee_rate is not null");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateEqualTo(BigDecimal value) {
            addCriterion("spot_fee_rate =", value, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("spot_fee_rate <>", value, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateGreaterThan(BigDecimal value) {
            addCriterion("spot_fee_rate >", value, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("spot_fee_rate >=", value, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateLessThan(BigDecimal value) {
            addCriterion("spot_fee_rate <", value, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("spot_fee_rate <=", value, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateIn(List<BigDecimal> values) {
            addCriterion("spot_fee_rate in", values, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("spot_fee_rate not in", values, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spot_fee_rate between", value1, value2, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSpotFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spot_fee_rate not between", value1, value2, "spotFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateIsNull() {
            addCriterion("swap_fee_rate is null");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateIsNotNull() {
            addCriterion("swap_fee_rate is not null");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateEqualTo(BigDecimal value) {
            addCriterion("swap_fee_rate =", value, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("swap_fee_rate <>", value, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateGreaterThan(BigDecimal value) {
            addCriterion("swap_fee_rate >", value, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("swap_fee_rate >=", value, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateLessThan(BigDecimal value) {
            addCriterion("swap_fee_rate <", value, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("swap_fee_rate <=", value, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateIn(List<BigDecimal> values) {
            addCriterion("swap_fee_rate in", values, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("swap_fee_rate not in", values, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("swap_fee_rate between", value1, value2, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andSwapFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("swap_fee_rate not between", value1, value2, "swapFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateIsNull() {
            addCriterion("margin_fee_rate is null");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateIsNotNull() {
            addCriterion("margin_fee_rate is not null");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateEqualTo(BigDecimal value) {
            addCriterion("margin_fee_rate =", value, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("margin_fee_rate <>", value, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateGreaterThan(BigDecimal value) {
            addCriterion("margin_fee_rate >", value, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("margin_fee_rate >=", value, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateLessThan(BigDecimal value) {
            addCriterion("margin_fee_rate <", value, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("margin_fee_rate <=", value, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateIn(List<BigDecimal> values) {
            addCriterion("margin_fee_rate in", values, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("margin_fee_rate not in", values, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("margin_fee_rate between", value1, value2, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andMarginFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("margin_fee_rate not between", value1, value2, "marginFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateIsNull() {
            addCriterion("algorithmic_fee_rate is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateIsNotNull() {
            addCriterion("algorithmic_fee_rate is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateEqualTo(BigDecimal value) {
            addCriterion("algorithmic_fee_rate =", value, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("algorithmic_fee_rate <>", value, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateGreaterThan(BigDecimal value) {
            addCriterion("algorithmic_fee_rate >", value, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("algorithmic_fee_rate >=", value, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateLessThan(BigDecimal value) {
            addCriterion("algorithmic_fee_rate <", value, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("algorithmic_fee_rate <=", value, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateIn(List<BigDecimal> values) {
            addCriterion("algorithmic_fee_rate in", values, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("algorithmic_fee_rate not in", values, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("algorithmic_fee_rate between", value1, value2, "algorithmicFeeRate");
            return (Criteria) this;
        }

        public Criteria andAlgorithmicFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("algorithmic_fee_rate not between", value1, value2, "algorithmicFeeRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_fee_config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}