package com.google.backend.trading.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   负余额资金费用表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_negative_balance_funding_cost
 */
public class TradeNegativeBalanceFundingCost implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   pending, completed
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   计算funding cost的数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.quantity
     *
     * @mbg.generated
     */
    private BigDecimal quantity;

    /**
     * Database Column Remarks:
     *   资金费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.funding_cost
     *
     * @mbg.generated
     */
    private BigDecimal fundingCost;

    /**
     * Database Column Remarks:
     *   币种
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.coin
     *
     * @mbg.generated
     */
    private String coin;

    /**
     * Database Column Remarks:
     *   计算资金费用的price
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.mtime
     *
     * @mbg.generated
     */
    private Date mtime;

    /**
     * Database Column Remarks:
     *   用户借出利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.lend
     *
     * @mbg.generated
     */
    private BigDecimal lend;

    /**
     * Database Column Remarks:
     *   用户借入利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.borrow
     *
     * @mbg.generated
     */
    private BigDecimal borrow;

    /**
     * Database Column Remarks:
     *   收取资金费率轮次的时间点（毫秒时间戳）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_negative_balance_funding_cost.round
     *
     * @mbg.generated
     */
    private Long round;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.id
     *
     * @return the value of trade_negative_balance_funding_cost.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.id
     *
     * @param id the value for trade_negative_balance_funding_cost.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.uuid
     *
     * @return the value of trade_negative_balance_funding_cost.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.uuid
     *
     * @param uuid the value for trade_negative_balance_funding_cost.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.uid
     *
     * @return the value of trade_negative_balance_funding_cost.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.uid
     *
     * @param uid the value for trade_negative_balance_funding_cost.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.status
     *
     * @return the value of trade_negative_balance_funding_cost.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.status
     *
     * @param status the value for trade_negative_balance_funding_cost.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.quantity
     *
     * @return the value of trade_negative_balance_funding_cost.quantity
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.quantity
     *
     * @param quantity the value for trade_negative_balance_funding_cost.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.funding_cost
     *
     * @return the value of trade_negative_balance_funding_cost.funding_cost
     *
     * @mbg.generated
     */
    public BigDecimal getFundingCost() {
        return fundingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.funding_cost
     *
     * @param fundingCost the value for trade_negative_balance_funding_cost.funding_cost
     *
     * @mbg.generated
     */
    public void setFundingCost(BigDecimal fundingCost) {
        this.fundingCost = fundingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.coin
     *
     * @return the value of trade_negative_balance_funding_cost.coin
     *
     * @mbg.generated
     */
    public String getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.coin
     *
     * @param coin the value for trade_negative_balance_funding_cost.coin
     *
     * @mbg.generated
     */
    public void setCoin(String coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.price
     *
     * @return the value of trade_negative_balance_funding_cost.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.price
     *
     * @param price the value for trade_negative_balance_funding_cost.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.ctime
     *
     * @return the value of trade_negative_balance_funding_cost.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.ctime
     *
     * @param ctime the value for trade_negative_balance_funding_cost.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.mtime
     *
     * @return the value of trade_negative_balance_funding_cost.mtime
     *
     * @mbg.generated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.mtime
     *
     * @param mtime the value for trade_negative_balance_funding_cost.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.lend
     *
     * @return the value of trade_negative_balance_funding_cost.lend
     *
     * @mbg.generated
     */
    public BigDecimal getLend() {
        return lend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.lend
     *
     * @param lend the value for trade_negative_balance_funding_cost.lend
     *
     * @mbg.generated
     */
    public void setLend(BigDecimal lend) {
        this.lend = lend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.borrow
     *
     * @return the value of trade_negative_balance_funding_cost.borrow
     *
     * @mbg.generated
     */
    public BigDecimal getBorrow() {
        return borrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.borrow
     *
     * @param borrow the value for trade_negative_balance_funding_cost.borrow
     *
     * @mbg.generated
     */
    public void setBorrow(BigDecimal borrow) {
        this.borrow = borrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_negative_balance_funding_cost.round
     *
     * @return the value of trade_negative_balance_funding_cost.round
     *
     * @mbg.generated
     */
    public Long getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_negative_balance_funding_cost.round
     *
     * @param round the value for trade_negative_balance_funding_cost.round
     *
     * @mbg.generated
     */
    public void setRound(Long round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_negative_balance_funding_cost
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", uid=").append(uid);
        sb.append(", status=").append(status);
        sb.append(", quantity=").append(quantity);
        sb.append(", fundingCost=").append(fundingCost);
        sb.append(", coin=").append(coin);
        sb.append(", price=").append(price);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", lend=").append(lend);
        sb.append(", borrow=").append(borrow);
        sb.append(", round=").append(round);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}