package com.google.backend.trading.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   交易订单表（现货/杠杆）
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_spot_order
 */
public class TradeSpotOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   订单状态 PRE_TRIGGER  PENDING  EXECUTING  LOCKED COMPLETED CANCELLED CANCELLING PART_CANCELLED
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   订单类型 LIMIT MARKET STOP_LIMIT STOP_MARKET
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   订单来源 PLACED_BY_CLIENT(用户下单) LIQUIDATION(清算) AUTO_CONVERSION(盈亏转换) PLACED_BY_API(用户API下单) LOAN_LIDQUIDATION(借贷强平)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     * Database Column Remarks:
     *   订单策略
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.strategy
     *
     * @mbg.generated
     */
    private String strategy;

    /**
     * Database Column Remarks:
     *   币对（下划线分割小写）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * Database Column Remarks:
     *   方向 BUY  SELL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.direction
     *
     * @mbg.generated
     */
    private String direction;

    /**
     * Database Column Remarks:
     *   是否按照quote数量成交，否则是base数量成交
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.is_quote
     *
     * @mbg.generated
     */
    private Boolean isQuote;

    /**
     * Database Column Remarks:
     *   委托数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.quantity
     *
     * @mbg.generated
     */
    private BigDecimal quantity;

    /**
     * Database Column Remarks:
     *   锁定数额（维持订单成交的锁定金额）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.lock_amount
     *
     * @mbg.generated
     */
    private BigDecimal lockAmount;

    /**
     * Database Column Remarks:
     *   for LIMIT, STOP_LIMIT 委托价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   委托数量中已成交数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.quantity_filled
     *
     * @mbg.generated
     */
    private BigDecimal quantityFilled;

    /**
     * Database Column Remarks:
     *   交易数量中已成交数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.amount_filled
     *
     * @mbg.generated
     */
    private BigDecimal amountFilled;

    /**
     * Database Column Remarks:
     *   成交均价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.filled_price
     *
     * @mbg.generated
     */
    private BigDecimal filledPrice;

    /**
     * Database Column Remarks:
     *   for STOP_LIMIT, STOP_MARKET 触发价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.trigger_price
     *
     * @mbg.generated
     */
    private BigDecimal triggerPrice;

    /**
     * Database Column Remarks:
     *   for STOP_LIMIT, STOP_MARKET，值为 > , < 意为当前价大于等于/小于等于触发价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.trigger_compare
     *
     * @mbg.generated
     */
    private String triggerCompare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.fee
     *
     * @mbg.generated
     */
    private BigDecimal fee;

    /**
     * Database Column Remarks:
     *   订单备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     * Database Column Remarks:
     *   错误说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.error
     *
     * @mbg.generated
     */
    private String error;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.mtime
     *
     * @mbg.generated
     */
    private Date mtime;

    /**
     * Database Column Remarks:
     *   手续费币种
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.fee_coin
     *
     * @mbg.generated
     */
    private String feeCoin;

    /**
     * Database Column Remarks:
     *   结束订单者 CLIENT 客户，RISK 风控系统
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.terminator
     *
     * @mbg.generated
     */
    private String terminator;

    /**
     * Database Column Remarks:
     *   交易id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_spot_order.trans_id
     *
     * @mbg.generated
     */
    private String transId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.id
     *
     * @return the value of trade_spot_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.id
     *
     * @param id the value for trade_spot_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.uuid
     *
     * @return the value of trade_spot_order.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.uuid
     *
     * @param uuid the value for trade_spot_order.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.uid
     *
     * @return the value of trade_spot_order.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.uid
     *
     * @param uid the value for trade_spot_order.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.status
     *
     * @return the value of trade_spot_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.status
     *
     * @param status the value for trade_spot_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.type
     *
     * @return the value of trade_spot_order.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.type
     *
     * @param type the value for trade_spot_order.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.source
     *
     * @return the value of trade_spot_order.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.source
     *
     * @param source the value for trade_spot_order.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.strategy
     *
     * @return the value of trade_spot_order.strategy
     *
     * @mbg.generated
     */
    public String getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.strategy
     *
     * @param strategy the value for trade_spot_order.strategy
     *
     * @mbg.generated
     */
    public void setStrategy(String strategy) {
        this.strategy = strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.symbol
     *
     * @return the value of trade_spot_order.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.symbol
     *
     * @param symbol the value for trade_spot_order.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.direction
     *
     * @return the value of trade_spot_order.direction
     *
     * @mbg.generated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.direction
     *
     * @param direction the value for trade_spot_order.direction
     *
     * @mbg.generated
     */
    public void setDirection(String direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.is_quote
     *
     * @return the value of trade_spot_order.is_quote
     *
     * @mbg.generated
     */
    public Boolean getIsQuote() {
        return isQuote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.is_quote
     *
     * @param isQuote the value for trade_spot_order.is_quote
     *
     * @mbg.generated
     */
    public void setIsQuote(Boolean isQuote) {
        this.isQuote = isQuote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.quantity
     *
     * @return the value of trade_spot_order.quantity
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.quantity
     *
     * @param quantity the value for trade_spot_order.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.lock_amount
     *
     * @return the value of trade_spot_order.lock_amount
     *
     * @mbg.generated
     */
    public BigDecimal getLockAmount() {
        return lockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.lock_amount
     *
     * @param lockAmount the value for trade_spot_order.lock_amount
     *
     * @mbg.generated
     */
    public void setLockAmount(BigDecimal lockAmount) {
        this.lockAmount = lockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.price
     *
     * @return the value of trade_spot_order.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.price
     *
     * @param price the value for trade_spot_order.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.quantity_filled
     *
     * @return the value of trade_spot_order.quantity_filled
     *
     * @mbg.generated
     */
    public BigDecimal getQuantityFilled() {
        return quantityFilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.quantity_filled
     *
     * @param quantityFilled the value for trade_spot_order.quantity_filled
     *
     * @mbg.generated
     */
    public void setQuantityFilled(BigDecimal quantityFilled) {
        this.quantityFilled = quantityFilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.amount_filled
     *
     * @return the value of trade_spot_order.amount_filled
     *
     * @mbg.generated
     */
    public BigDecimal getAmountFilled() {
        return amountFilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.amount_filled
     *
     * @param amountFilled the value for trade_spot_order.amount_filled
     *
     * @mbg.generated
     */
    public void setAmountFilled(BigDecimal amountFilled) {
        this.amountFilled = amountFilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.filled_price
     *
     * @return the value of trade_spot_order.filled_price
     *
     * @mbg.generated
     */
    public BigDecimal getFilledPrice() {
        return filledPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.filled_price
     *
     * @param filledPrice the value for trade_spot_order.filled_price
     *
     * @mbg.generated
     */
    public void setFilledPrice(BigDecimal filledPrice) {
        this.filledPrice = filledPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.trigger_price
     *
     * @return the value of trade_spot_order.trigger_price
     *
     * @mbg.generated
     */
    public BigDecimal getTriggerPrice() {
        return triggerPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.trigger_price
     *
     * @param triggerPrice the value for trade_spot_order.trigger_price
     *
     * @mbg.generated
     */
    public void setTriggerPrice(BigDecimal triggerPrice) {
        this.triggerPrice = triggerPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.trigger_compare
     *
     * @return the value of trade_spot_order.trigger_compare
     *
     * @mbg.generated
     */
    public String getTriggerCompare() {
        return triggerCompare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.trigger_compare
     *
     * @param triggerCompare the value for trade_spot_order.trigger_compare
     *
     * @mbg.generated
     */
    public void setTriggerCompare(String triggerCompare) {
        this.triggerCompare = triggerCompare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.fee
     *
     * @return the value of trade_spot_order.fee
     *
     * @mbg.generated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.fee
     *
     * @param fee the value for trade_spot_order.fee
     *
     * @mbg.generated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.notes
     *
     * @return the value of trade_spot_order.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.notes
     *
     * @param notes the value for trade_spot_order.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.error
     *
     * @return the value of trade_spot_order.error
     *
     * @mbg.generated
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.error
     *
     * @param error the value for trade_spot_order.error
     *
     * @mbg.generated
     */
    public void setError(String error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.ctime
     *
     * @return the value of trade_spot_order.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.ctime
     *
     * @param ctime the value for trade_spot_order.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.mtime
     *
     * @return the value of trade_spot_order.mtime
     *
     * @mbg.generated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.mtime
     *
     * @param mtime the value for trade_spot_order.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.fee_coin
     *
     * @return the value of trade_spot_order.fee_coin
     *
     * @mbg.generated
     */
    public String getFeeCoin() {
        return feeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.fee_coin
     *
     * @param feeCoin the value for trade_spot_order.fee_coin
     *
     * @mbg.generated
     */
    public void setFeeCoin(String feeCoin) {
        this.feeCoin = feeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.terminator
     *
     * @return the value of trade_spot_order.terminator
     *
     * @mbg.generated
     */
    public String getTerminator() {
        return terminator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.terminator
     *
     * @param terminator the value for trade_spot_order.terminator
     *
     * @mbg.generated
     */
    public void setTerminator(String terminator) {
        this.terminator = terminator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_spot_order.trans_id
     *
     * @return the value of trade_spot_order.trans_id
     *
     * @mbg.generated
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_spot_order.trans_id
     *
     * @param transId the value for trade_spot_order.trans_id
     *
     * @mbg.generated
     */
    public void setTransId(String transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_spot_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", uid=").append(uid);
        sb.append(", status=").append(status);
        sb.append(", type=").append(type);
        sb.append(", source=").append(source);
        sb.append(", strategy=").append(strategy);
        sb.append(", symbol=").append(symbol);
        sb.append(", direction=").append(direction);
        sb.append(", isQuote=").append(isQuote);
        sb.append(", quantity=").append(quantity);
        sb.append(", lockAmount=").append(lockAmount);
        sb.append(", price=").append(price);
        sb.append(", quantityFilled=").append(quantityFilled);
        sb.append(", amountFilled=").append(amountFilled);
        sb.append(", filledPrice=").append(filledPrice);
        sb.append(", triggerPrice=").append(triggerPrice);
        sb.append(", triggerCompare=").append(triggerCompare);
        sb.append(", fee=").append(fee);
        sb.append(", notes=").append(notes);
        sb.append(", error=").append(error);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", feeCoin=").append(feeCoin);
        sb.append(", terminator=").append(terminator);
        sb.append(", transId=").append(transId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}