package com.google.backend.trading.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   兑换订单
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_swap_order
 */
public class TradeSwapOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   支付的币种
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.from_coin
     *
     * @mbg.generated
     */
    private String fromCoin;

    /**
     * Database Column Remarks:
     *   获得的币种
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.to_coin
     *
     * @mbg.generated
     */
    private String toCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.fee
     *
     * @mbg.generated
     */
    private BigDecimal fee;

    /**
     * Database Column Remarks:
     *   兑换方式 PAYMENT: 委托支付（固定支付）  OBTAINED：委托获得（固定获得） 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.mode
     *
     * @mbg.generated
     */
    private String mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal feeRate;

    /**
     * Database Column Remarks:
     *   下单时的价格（支付币种/获得币种）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.order_price
     *
     * @mbg.generated
     */
    private BigDecimal orderPrice;

    /**
     * Database Column Remarks:
     *   成交价格（支付币种/获得币种）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.deal_price
     *
     * @mbg.generated
     */
    private BigDecimal dealPrice;

    /**
     * Database Column Remarks:
     * 订单状态 PENDING EXECUTING LOCKED AIP_LOCKED(定投业务) COMPLETED CANCELED
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   状态为 ERROR 时有对应备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.mtime
     *
     * @mbg.generated
     */
    private Date mtime;

    /**
     * Database Column Remarks:
     *   支付数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.from_quantity
     *
     * @mbg.generated
     */
    private BigDecimal fromQuantity;

    /**
     * Database Column Remarks:
     *   获得数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.to_quantity
     *
     * @mbg.generated
     */
    private BigDecimal toQuantity;

    /**
     * Database Column Remarks:
     *   订单来源 PLACED_BY_CLIENT(用户下单) REPAY_WITH_COLLATERAL(借贷质押还款订单)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     * Database Column Remarks:
     *   手续费币种
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.fee_coin
     *
     * @mbg.generated
     */
    private String feeCoin;

    /**
     * Database Column Remarks:
     * 交易ID（只有AIP定投业务使用）
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_swap_order.trans_id
     *
     * @mbg.generated
     */
    private String transId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.id
     *
     * @return the value of trade_swap_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.id
     *
     * @param id the value for trade_swap_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.uuid
     *
     * @return the value of trade_swap_order.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.uuid
     *
     * @param uuid the value for trade_swap_order.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.uid
     *
     * @return the value of trade_swap_order.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.uid
     *
     * @param uid the value for trade_swap_order.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.from_coin
     *
     * @return the value of trade_swap_order.from_coin
     *
     * @mbg.generated
     */
    public String getFromCoin() {
        return fromCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.from_coin
     *
     * @param fromCoin the value for trade_swap_order.from_coin
     *
     * @mbg.generated
     */
    public void setFromCoin(String fromCoin) {
        this.fromCoin = fromCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.to_coin
     *
     * @return the value of trade_swap_order.to_coin
     *
     * @mbg.generated
     */
    public String getToCoin() {
        return toCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.to_coin
     *
     * @param toCoin the value for trade_swap_order.to_coin
     *
     * @mbg.generated
     */
    public void setToCoin(String toCoin) {
        this.toCoin = toCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.fee
     *
     * @return the value of trade_swap_order.fee
     *
     * @mbg.generated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.fee
     *
     * @param fee the value for trade_swap_order.fee
     *
     * @mbg.generated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.mode
     *
     * @return the value of trade_swap_order.mode
     *
     * @mbg.generated
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.mode
     *
     * @param mode the value for trade_swap_order.mode
     *
     * @mbg.generated
     */
    public void setMode(String mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.fee_rate
     *
     * @return the value of trade_swap_order.fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.fee_rate
     *
     * @param feeRate the value for trade_swap_order.fee_rate
     *
     * @mbg.generated
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.order_price
     *
     * @return the value of trade_swap_order.order_price
     *
     * @mbg.generated
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.order_price
     *
     * @param orderPrice the value for trade_swap_order.order_price
     *
     * @mbg.generated
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.deal_price
     *
     * @return the value of trade_swap_order.deal_price
     *
     * @mbg.generated
     */
    public BigDecimal getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.deal_price
     *
     * @param dealPrice the value for trade_swap_order.deal_price
     *
     * @mbg.generated
     */
    public void setDealPrice(BigDecimal dealPrice) {
        this.dealPrice = dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.status
     *
     * @return the value of trade_swap_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.status
     *
     * @param status the value for trade_swap_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.memo
     *
     * @return the value of trade_swap_order.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.memo
     *
     * @param memo the value for trade_swap_order.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.ctime
     *
     * @return the value of trade_swap_order.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.ctime
     *
     * @param ctime the value for trade_swap_order.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.mtime
     *
     * @return the value of trade_swap_order.mtime
     *
     * @mbg.generated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.mtime
     *
     * @param mtime the value for trade_swap_order.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.from_quantity
     *
     * @return the value of trade_swap_order.from_quantity
     *
     * @mbg.generated
     */
    public BigDecimal getFromQuantity() {
        return fromQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.from_quantity
     *
     * @param fromQuantity the value for trade_swap_order.from_quantity
     *
     * @mbg.generated
     */
    public void setFromQuantity(BigDecimal fromQuantity) {
        this.fromQuantity = fromQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.to_quantity
     *
     * @return the value of trade_swap_order.to_quantity
     *
     * @mbg.generated
     */
    public BigDecimal getToQuantity() {
        return toQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.to_quantity
     *
     * @param toQuantity the value for trade_swap_order.to_quantity
     *
     * @mbg.generated
     */
    public void setToQuantity(BigDecimal toQuantity) {
        this.toQuantity = toQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.source
     *
     * @return the value of trade_swap_order.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.source
     *
     * @param source the value for trade_swap_order.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.fee_coin
     *
     * @return the value of trade_swap_order.fee_coin
     *
     * @mbg.generated
     */
    public String getFeeCoin() {
        return feeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.fee_coin
     *
     * @param feeCoin the value for trade_swap_order.fee_coin
     *
     * @mbg.generated
     */
    public void setFeeCoin(String feeCoin) {
        this.feeCoin = feeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_swap_order.trans_id
     *
     * @return the value of trade_swap_order.trans_id
     * @mbg.generated
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_swap_order.trans_id
     *
     * @param transId the value for trade_swap_order.trans_id
     * @mbg.generated
     */
    public void setTransId(String transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_swap_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", uid=").append(uid);
        sb.append(", fromCoin=").append(fromCoin);
        sb.append(", toCoin=").append(toCoin);
        sb.append(", fee=").append(fee);
        sb.append(", mode=").append(mode);
        sb.append(", feeRate=").append(feeRate);
        sb.append(", orderPrice=").append(orderPrice);
        sb.append(", dealPrice=").append(dealPrice);
        sb.append(", status=").append(status);
        sb.append(", memo=").append(memo);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", fromQuantity=").append(fromQuantity);
        sb.append(", toQuantity=").append(toQuantity);
        sb.append(", source=").append(source);
        sb.append(", feeCoin=").append(feeCoin);
        sb.append(", transId=").append(transId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}