package com.google.backend.trading.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   杠杆仓位表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_position
 */
public class TradePosition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   仓位状态 active close
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   币对（下划线分割小写）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * Database Column Remarks:
     *   方向 long short
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.direction
     *
     * @mbg.generated
     */
    private String direction;

    /**
     * Database Column Remarks:
     *   持仓数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.quantity
     *
     * @mbg.generated
     */
    private BigDecimal quantity;

    /**
     * Database Column Remarks:
     *   仓位成交均价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   是否自动交割
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.auto_settle
     *
     * @mbg.generated
     */
    private Boolean autoSettle;

    /**
     * Database Column Remarks:
     *   止损价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.stop_loss_price
     *
     * @mbg.generated
     */
    private BigDecimal stopLossPrice;

    /**
     * Database Column Remarks:
     *   止损占仓位比，默认0，表示不开启止损
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.stop_loss_percentage
     *
     * @mbg.generated
     */
    private BigDecimal stopLossPercentage;

    /**
     * Database Column Remarks:
     *   止盈价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.take_profit_price
     *
     * @mbg.generated
     */
    private BigDecimal takeProfitPrice;

    /**
     * Database Column Remarks:
     *   止盈占仓位比，默认0，表示不开启止盈
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.take_profit_percentage
     *
     * @mbg.generated
     */
    private BigDecimal takeProfitPercentage;

    /**
     * Database Column Remarks:
     *   最大持仓数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.max_quantity
     *
     * @mbg.generated
     */
    private BigDecimal maxQuantity;

    /**
     * Database Column Remarks:
     *   仓位已实现pnl（包括资金费率和手续费）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.pnl
     *
     * @mbg.generated
     */
    private BigDecimal pnl;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.mtime
     *
     * @mbg.generated
     */
    private Date mtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_position.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.id
     *
     * @return the value of trade_position.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.id
     *
     * @param id the value for trade_position.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.uid
     *
     * @return the value of trade_position.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.uid
     *
     * @param uid the value for trade_position.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.status
     *
     * @return the value of trade_position.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.status
     *
     * @param status the value for trade_position.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.symbol
     *
     * @return the value of trade_position.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.symbol
     *
     * @param symbol the value for trade_position.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.direction
     *
     * @return the value of trade_position.direction
     *
     * @mbg.generated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.direction
     *
     * @param direction the value for trade_position.direction
     *
     * @mbg.generated
     */
    public void setDirection(String direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.quantity
     *
     * @return the value of trade_position.quantity
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.quantity
     *
     * @param quantity the value for trade_position.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.price
     *
     * @return the value of trade_position.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.price
     *
     * @param price the value for trade_position.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.auto_settle
     *
     * @return the value of trade_position.auto_settle
     *
     * @mbg.generated
     */
    public Boolean getAutoSettle() {
        return autoSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.auto_settle
     *
     * @param autoSettle the value for trade_position.auto_settle
     *
     * @mbg.generated
     */
    public void setAutoSettle(Boolean autoSettle) {
        this.autoSettle = autoSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.stop_loss_price
     *
     * @return the value of trade_position.stop_loss_price
     *
     * @mbg.generated
     */
    public BigDecimal getStopLossPrice() {
        return stopLossPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.stop_loss_price
     *
     * @param stopLossPrice the value for trade_position.stop_loss_price
     *
     * @mbg.generated
     */
    public void setStopLossPrice(BigDecimal stopLossPrice) {
        this.stopLossPrice = stopLossPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.stop_loss_percentage
     *
     * @return the value of trade_position.stop_loss_percentage
     *
     * @mbg.generated
     */
    public BigDecimal getStopLossPercentage() {
        return stopLossPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.stop_loss_percentage
     *
     * @param stopLossPercentage the value for trade_position.stop_loss_percentage
     *
     * @mbg.generated
     */
    public void setStopLossPercentage(BigDecimal stopLossPercentage) {
        this.stopLossPercentage = stopLossPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.take_profit_price
     *
     * @return the value of trade_position.take_profit_price
     *
     * @mbg.generated
     */
    public BigDecimal getTakeProfitPrice() {
        return takeProfitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.take_profit_price
     *
     * @param takeProfitPrice the value for trade_position.take_profit_price
     *
     * @mbg.generated
     */
    public void setTakeProfitPrice(BigDecimal takeProfitPrice) {
        this.takeProfitPrice = takeProfitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.take_profit_percentage
     *
     * @return the value of trade_position.take_profit_percentage
     *
     * @mbg.generated
     */
    public BigDecimal getTakeProfitPercentage() {
        return takeProfitPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.take_profit_percentage
     *
     * @param takeProfitPercentage the value for trade_position.take_profit_percentage
     *
     * @mbg.generated
     */
    public void setTakeProfitPercentage(BigDecimal takeProfitPercentage) {
        this.takeProfitPercentage = takeProfitPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.max_quantity
     *
     * @return the value of trade_position.max_quantity
     *
     * @mbg.generated
     */
    public BigDecimal getMaxQuantity() {
        return maxQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.max_quantity
     *
     * @param maxQuantity the value for trade_position.max_quantity
     *
     * @mbg.generated
     */
    public void setMaxQuantity(BigDecimal maxQuantity) {
        this.maxQuantity = maxQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.pnl
     *
     * @return the value of trade_position.pnl
     *
     * @mbg.generated
     */
    public BigDecimal getPnl() {
        return pnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.pnl
     *
     * @param pnl the value for trade_position.pnl
     *
     * @mbg.generated
     */
    public void setPnl(BigDecimal pnl) {
        this.pnl = pnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.ctime
     *
     * @return the value of trade_position.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.ctime
     *
     * @param ctime the value for trade_position.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.mtime
     *
     * @return the value of trade_position.mtime
     *
     * @mbg.generated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.mtime
     *
     * @param mtime the value for trade_position.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_position.uuid
     *
     * @return the value of trade_position.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_position.uuid
     *
     * @param uuid the value for trade_position.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_position
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", status=").append(status);
        sb.append(", symbol=").append(symbol);
        sb.append(", direction=").append(direction);
        sb.append(", quantity=").append(quantity);
        sb.append(", price=").append(price);
        sb.append(", autoSettle=").append(autoSettle);
        sb.append(", stopLossPrice=").append(stopLossPrice);
        sb.append(", stopLossPercentage=").append(stopLossPercentage);
        sb.append(", takeProfitPrice=").append(takeProfitPrice);
        sb.append(", takeProfitPercentage=").append(takeProfitPercentage);
        sb.append(", maxQuantity=").append(maxQuantity);
        sb.append(", pnl=").append(pnl);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", uuid=").append(uuid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}