package com.google.backend.trading.dao.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_coin_watch_list
 */
public class TradeCoinWatchList implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coin_watch_list.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coin_watch_list.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   关注币种数组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coin_watch_list.watch_arr
     *
     * @mbg.generated
     */
    private Object watchArr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_coin_watch_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coin_watch_list.id
     *
     * @return the value of trade_coin_watch_list.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coin_watch_list.id
     *
     * @param id the value for trade_coin_watch_list.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coin_watch_list.uid
     *
     * @return the value of trade_coin_watch_list.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coin_watch_list.uid
     *
     * @param uid the value for trade_coin_watch_list.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coin_watch_list.watch_arr
     *
     * @return the value of trade_coin_watch_list.watch_arr
     *
     * @mbg.generated
     */
    public Object getWatchArr() {
        return watchArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coin_watch_list.watch_arr
     *
     * @param watchArr the value for trade_coin_watch_list.watch_arr
     *
     * @mbg.generated
     */
    public void setWatchArr(Object watchArr) {
        this.watchArr = watchArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coin_watch_list
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", watchArr=").append(watchArr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}