package com.google.backend.trading.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   交易手续费配置
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_fee_config
 */
public class TradeFeeConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_fee_config.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   现货手续费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_fee_config.spot_fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal spotFeeRate;

    /**
     * Database Column Remarks:
     *   兑换手续费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_fee_config.swap_fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal swapFeeRate;

    /**
     * Database Column Remarks:
     *   杠杆手续费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_fee_config.margin_fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal marginFeeRate;

    /**
     * Database Column Remarks:
     *   算法手续费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_fee_config.algorithmic_fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal algorithmicFeeRate;

    /**
     * Database Column Remarks:
     *   资金费用比例,一般只有 1 和 0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_fee_config.funding_cost_rate
     *
     * @mbg.generated
     */
    private BigDecimal fundingCostRate;

    /**
     * Database Column Remarks:
     *   交割服务费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_fee_config.margin_settle_fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal marginSettleFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_fee_config.id
     *
     * @return the value of trade_fee_config.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_fee_config.id
     *
     * @param id the value for trade_fee_config.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_fee_config.spot_fee_rate
     *
     * @return the value of trade_fee_config.spot_fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getSpotFeeRate() {
        return spotFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_fee_config.spot_fee_rate
     *
     * @param spotFeeRate the value for trade_fee_config.spot_fee_rate
     *
     * @mbg.generated
     */
    public void setSpotFeeRate(BigDecimal spotFeeRate) {
        this.spotFeeRate = spotFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_fee_config.swap_fee_rate
     *
     * @return the value of trade_fee_config.swap_fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getSwapFeeRate() {
        return swapFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_fee_config.swap_fee_rate
     *
     * @param swapFeeRate the value for trade_fee_config.swap_fee_rate
     *
     * @mbg.generated
     */
    public void setSwapFeeRate(BigDecimal swapFeeRate) {
        this.swapFeeRate = swapFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_fee_config.margin_fee_rate
     *
     * @return the value of trade_fee_config.margin_fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getMarginFeeRate() {
        return marginFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_fee_config.margin_fee_rate
     *
     * @param marginFeeRate the value for trade_fee_config.margin_fee_rate
     *
     * @mbg.generated
     */
    public void setMarginFeeRate(BigDecimal marginFeeRate) {
        this.marginFeeRate = marginFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_fee_config.algorithmic_fee_rate
     *
     * @return the value of trade_fee_config.algorithmic_fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getAlgorithmicFeeRate() {
        return algorithmicFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_fee_config.algorithmic_fee_rate
     *
     * @param algorithmicFeeRate the value for trade_fee_config.algorithmic_fee_rate
     *
     * @mbg.generated
     */
    public void setAlgorithmicFeeRate(BigDecimal algorithmicFeeRate) {
        this.algorithmicFeeRate = algorithmicFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_fee_config.funding_cost_rate
     *
     * @return the value of trade_fee_config.funding_cost_rate
     *
     * @mbg.generated
     */
    public BigDecimal getFundingCostRate() {
        return fundingCostRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_fee_config.funding_cost_rate
     *
     * @param fundingCostRate the value for trade_fee_config.funding_cost_rate
     *
     * @mbg.generated
     */
    public void setFundingCostRate(BigDecimal fundingCostRate) {
        this.fundingCostRate = fundingCostRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_fee_config.margin_settle_fee_rate
     *
     * @return the value of trade_fee_config.margin_settle_fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getMarginSettleFeeRate() {
        return marginSettleFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_fee_config.margin_settle_fee_rate
     *
     * @param marginSettleFeeRate the value for trade_fee_config.margin_settle_fee_rate
     *
     * @mbg.generated
     */
    public void setMarginSettleFeeRate(BigDecimal marginSettleFeeRate) {
        this.marginSettleFeeRate = marginSettleFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_fee_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", spotFeeRate=").append(spotFeeRate);
        sb.append(", swapFeeRate=").append(swapFeeRate);
        sb.append(", marginFeeRate=").append(marginFeeRate);
        sb.append(", algorithmicFeeRate=").append(algorithmicFeeRate);
        sb.append(", fundingCostRate=").append(fundingCostRate);
        sb.append(", marginSettleFeeRate=").append(marginSettleFeeRate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}