package com.google.backend.trading.model.config.api;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.hibernate.validator.constraints.Range;

import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;
import java.math.BigDecimal;

/**
 * 用户交易设置
 *
 * @author adam.wang
 */
@Data
@ApiModel(value = "用户配置变更请求数据")
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class UserTradeSettingUpdateReq {


	/**
	 * Database Column Remarks:
	 * 杠杆倍数
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.leverage
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "调整杠杆", example = "5")
	@Range(min = 1, max = 5)
	private Integer leverage;

	/**
	 * Database Column Remarks:
	 * 全仓止损
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.max_loss
	 *
	 * @mbg.generated
	 */
	@Digits(integer = 16, fraction = 2)
	@DecimalMin(value = "0")
	@ApiModelProperty(name = "max_loss", value = "全仓止损，关闭时传0", example = "1")
	private BigDecimal maxLoss;

	/**
	 * Database Column Remarks:
	 * 全仓止盈
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.take_profit
	 *
	 * @mbg.generated
	 */
	@Digits(integer = 16, fraction = 2)
	@DecimalMin(value = "0")
	@ApiModelProperty(name = "take_profit", value = "全仓止盈，关闭时传0", example = "1")
	private BigDecimal takeProfit;

	/**
	 * Database Column Remarks:
	 * 理财质押
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.earn_pledge
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "earn_pledge", value = "理财资产质押", example = "true")
	private Boolean earnPledge;

	/**
	 * Database Column Remarks:
	 * 结算时区
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.settle_time_zone
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "settle_time_zone_id", value = "结算时区", example = "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi")
	private String settleTimeZoneId;

	/**
	 * Database Column Remarks:
	 * 自动交割
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.auto_settle
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "auto_settle", value = "全局自动交割", example = "true")
	private Boolean autoSettle;

	/**
	 * Database Column Remarks:
	 * 自动平负余额
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.auto_fix_negative
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "auto_fix_negative", value = "自动平负余额", example = "true")
	private Boolean autoFixNegative;

	/**
	 * Database Column Remarks:
	 * 清算理财资产
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.liquid_earn
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "liquid_earn", value = "自动清算理财资产", example = "true")
	private Boolean liquidEarn;

	/**
	 * 邮件通知
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.email_notification
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "email_notification", value = "邮件通知", example = "true")
	private Boolean emailNotification;

	/**
	 * Database Column Remarks:
	 * 订单二次确认
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.reconfirm_order
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "reconfirm_order", value = "二次确认", example = "true")
	private Boolean reconfirmOrder;


	/**
	 * Database Column Remarks:
	 * 双击下单
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.double_click_place_order
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "double_click_place_order", value = "双击下单", example = "true")
	private Boolean doubleClickPlaceOrder;

	/**
	 * Database Column Remarks:
	 * 自动转换
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column trade_user_trade_setting.auto_convert
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(name = "auto_convert", value = "自动转换", example = "true")
	private Boolean autoConvert;

}